### ISSUE TITLE
Can we expose `imagesToIco` function please?

### ISSUE THREAD

**Issue by wdanilo** [steambap/png-to-ico#10]
I have an use case where I have already different PNG sizes and I do not need auto resizing. There are several reasons for such situation - e.g. different sizes should have different details. I would love to use this library but I need to provide a list of png files to it. Could we expose such functionality?

**Comment by steambap** [comment]
The imagesToIco function only accept an array of Jimp image as input and it is not easy to use. I have added support for list of file path as input, you can use it like this:

```JavaScript
const fs = require('fs');
const pngToIco = require('png-to-ico');

pngToIco(['electron256x256.png', 'electron64x64.png', 'electron16x16.png'])
  .then(buf => {
    fs.writeFileSync('app.ico', buf);
  })
  .catch(console.error);
```

Can you try the new version (v2.1.0) and give me some feedbacks?
