### ISSUE TITLE
你好，如何自定义ico图标大小呢？

### ISSUE THREAD

**Issue by ystcode** [steambap/png-to-ico#13]
在脚本本该如何写呢？

**Comment by steambap** [comment]
http://fileformats.wikia.com/wiki/Icon
图标文件中的 bmp 文件的大小是固定的，不知道你要改图标的什么的大小

**Comment by ystcode** [comment]
你这个项目不是png转ico吗？png是自己提供的，ico是程序输出的，我当然问的是ico图标的大小啊

**Comment by ystcode** [comment]
我理解的你的意思是输出的ico图标的大小固定为48x48，不可以自定义

**Comment by steambap** [comment]
我输出的是 icon 格式，内部的 bmp 文件为 256x256，48x48，32x32，16x16
