### ISSUE TITLE
生成的ico左下角异常

### ISSUE THREAD

**Issue by clys** [steambap/png-to-ico#14]
![截图录屏_选择区域_20201114160153](https://user-images.githubusercontent.com/9857824/99142719-c2c98700-2692-11eb-89ff-70891bc42bc5.png)

**Comment by clys** [comment]
发现是145-162行的代码导致的
直接删除这段代码就正常了

**Comment by steambap** [comment]
你可不可以提供一下你的图片。或者你用 GIMP 保存一下你的图片，看看有没有同样的问题。
