### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by hubortje** [steambap/png-to-ico#16]
Hey there,

I tried installing the script, but get the following npm warnings after the installation:

    npm WARN saveError ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
    npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
    npm WARN system32 No description
    npm WARN system32 No repository field.
    npm WARN system32 No README data
    npm WARN system32 No license field.

Furthermore, when I try running the script, I get the following errorcode:

    + CategoryInfo          : ObjectNotFound: (png-to-ico:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by steambap** [comment]
It looks like you are trying to install npm package in your system32 directory?

**Comment by hubortje** [comment]
I used this directory path as a placeholder.
I tried installing it in different directories, the error remains the same.

**Comment by steambap** [comment]
Maybe use cmd instead of the new powershell?

**Comment by hubortje** [comment]
Yields the same results.

**Comment by steambap** [comment]
Can you provide more info? Like which version of node.js are you using, version of npm, command you run, etc.
