### ISSUE TITLE
Using jimp-compact

### ISSUE THREAD

**Issue by pi0** [steambap/png-to-ico#17]
Hi! I just discovered this nice package today. I would suggest switching to [jimp-compact](https://github.com/unjs/jimp-compact) which is significantly smaller and potentially faster too.

**Comment by steambap** [comment]
Hi, thanks for pointing out a nicer alternative to JIMP.
For this package, I thinking of completely drop JIMP in favor of use pngjs directly. People are using my package to convert JPEG to ico, I don't want them to have something that is working half of the time.
