### ISSUE TITLE
electron-builder reports ico file is not valid Windows icon

### ISSUE THREAD

**Issue by navenedrob** [steambap/png-to-ico#2]
After trying a build and using converted ico as a part of the build.

Error: Windows icon is not valid ico file.

**Comment by steambap** [comment]
Which version of png-to-icon are you using?

I use electron-packager in my daytime job. If you have a minimal repo that reproduce the problem, it will be very helpful. Also, my God is telling this camplain came from squirrel.windows, which is written in c#. I probably have to look into that during this weekend.

**Comment by navenedrob** [comment]
@steambap I think the issue was during using icon-gen directly it was failing to produce a valid ico. I switched to using electron-icon-maker and now don't have the issue during my build. I filed an issue with icon-gen and am going to test it today.

At this time, I believe the message by electron-builder was true, and not an issue with electron-builder so I am closing this issue.

**Comment by steambap** [comment]
I just checked `icon-gen` repo. It looks like they have their own ico encoding code.

If `icon-gen` does not work or you do not want to generate all of the image size yourself, please give `png-to-ico` a try.
