### ISSUE TITLE
Image size is zero?

### ISSUE THREAD

**Issue by shtse8** [steambap/png-to-ico#20]
Hello, thanks for this incredible project so that I can convert my image to ico format in js without any third party library.

I am inspecting the code because some ico readers say the icon we generated is ill-formed. 
<img width="472" alt="image" src="https://user-images.githubusercontent.com/8020099/184526859-3a7ff0c9-9546-4cef-ba56-55e8d8970715.png">

Also, google search console cannot show my icon properly. while others are working well.

https://github.com/steambap/png-to-ico/blob/754b5bc864f5e8cf83c29549a05bd0f07b3786d2/index.js#L107

I found that the image size specified here is `0` and I think it should be equals to `size + andMapSize`. 

https://github.com/steambap/png-to-ico/blob/754b5bc864f5e8cf83c29549a05bd0f07b3786d2/index.js#L126

Another question is, comparing to [other libraries](https://github.com/kevva/to-ico/blob/f11c67edeec77d8722e3a2d0511c7684fcb208b8/index.js#L62-L87), we are doing `and map` here to pad all row into 32bits.
https://github.com/steambap/png-to-ico/blob/754b5bc864f5e8cf83c29549a05bd0f07b3786d2/index.js#L145-L163

Any references about that?

**Comment by steambap** [comment]
1. About the image size in BMP info header, wikipedia says a dummy 0 can be used here. https://en.wikipedia.org/wiki/BMP_file_format. I have never heard of google search console before, and I will try to reproduce it during weekend.
2. About the AND map. If it is not there, some online icon checker will complain. This portion of code was copied from GIMP, which is written in c. https://github.com/GNOME/gimp/blob/master/plug-ins/file-ico/ico-save.c

**Comment by shtse8** [comment]
> 1. About the image size in BMP info header, wikipedia says a dummy 0 can be used here. https://en.wikipedia.org/wiki/BMP_file_format. I have never heard of google search console before, and I will try to reproduce it during weekend.
> 2. About the AND map. If it is not there, some online icon checker will complain. This portion of code was copied from GIMP, which is written in c. https://github.com/GNOME/gimp/blob/master/plug-ins/file-ico/ico-save.c

Good point to take reference from GIMP. If I understand correctly, according to GIMP, the length of data wouldn't increase, xor-map and and-map are writing in the same space of buffer. but it seems we are writing after the data length.

extending the length with AND map
https://github.com/steambap/png-to-ico/blob/754b5bc864f5e8cf83c29549a05bd0f07b3786d2/index.js#L126
writing to position based on `size`
https://github.com/steambap/png-to-ico/blob/754b5bc864f5e8cf83c29549a05bd0f07b3786d2/index.js#L159


GIMP, always writing in the same space
https://github.com/GNOME/gimp/blob/94414c1ca8793b59f570dfe66fa01c81672139f2/plug-ins/file-ico/ico-save.c#L432
writing alpha channel with and map
https://github.com/GNOME/gimp/blob/94414c1ca8793b59f570dfe66fa01c81672139f2/plug-ins/file-ico/ico-save.c#L1014
check and map to see if we need to write black or palette
https://github.com/GNOME/gimp/blob/94414c1ca8793b59f570dfe66fa01c81672139f2/plug-ins/file-ico/ico-save.c#L1082-L1094

**Comment by steambap** [comment]
Hi, I just check my google search console. I see no place where the original website's icon should be displayed.
Also, I wonder what is the ico reader you are using?

**Comment by shtse8** [comment]
<img width="257" alt="image" src="https://user-images.githubusercontent.com/8020099/185749875-a211acb9-f811-4872-aacb-579c966224a9.png">

![image](https://user-images.githubusercontent.com/8020099/185749865-909bec3e-8c58-488e-b6bb-40c90ee6e64b.png)


https://realfavicongenerator.net/favicon_checker#.YwDplS7P0Q8

![image](https://user-images.githubusercontent.com/8020099/185749948-24bcb873-b0ab-446a-ba20-0743cddd5d1a.png)

but every others are fine. just these two places confusing me a lot.

**Comment by steambap** [comment]
I did not update the image size in icon directory after add the XOR map back in 2019. Now it should pass the check in real favicon generator if you use the latest build v2.1.5.

Strangely, they do not check the image size back in 2019 (#7).
