### ISSUE TITLE
Unable to use Buffer as input after Jimp -> pngjs replacement

### ISSUE THREAD

**Issue by m4rvr** [steambap/png-to-ico#24]
Hey!

Before it could create an .ico from a Buffer as input. After you switched from Jimp to pngjs it doesn't work anymore.
I'm getting `<file content> is not or a valid PNG file.`.

Is it possible to allow using Buffer as input again?

**Comment by steambap** [comment]
Hi, I have published a new version v2.1.8 to support buffer as input again.
