### ISSUE TITLE
Migrate to sharp

### ISSUE THREAD

**Issue by DanielRuf** [steambap/png-to-ico#5]
`sharp` is much faster and better, see https://sharp.pixelplumbing.com/en/stable/performance/

**Comment by steambap** [comment]
Looks like it is using a native library called libvps. If it is true, then I cannot use sharp since the goal of this repo is to not use any c++ add-on.

**Comment by DanielRuf** [comment]
The deps are bundled with the prebuilt releases and are built from source using `node-gyp` (which is bundled with NodeJS).

But my main concern is the performance and maintenance. sharp is used by many like Gatsby, open / closed issue ratio and how actively people contribute to it.

So far I never had issues with sharp.

**Comment by steambap** [comment]
Sorry, I hate them. In my previous job I've worked with node-canvas and in my current job I have some legacy code that runs node-memwatch. All of them have prebuilt release and can be built from source, but I wasted so much time on them that I don't want any more c++ add-on. I'm ok with c++ add-on if it is like Chokidar where the dependency is optional.

**Comment by psirenny** [comment]
This is an old thread, but I just wanted to add a few more thoughts. Sharp's prebuilt **libvips** library _doesn't_ support `.ico` files. In order to use sharp, **libvips** must separately be compiled globally with ImageMagick. Furthermore, sharp doesn't support globally compiled **libvips** on Windows. These are pretty big limitations to using sharp.

**Comment by shtse8** [comment]
> `sharp` is much faster and better, see https://sharp.pixelplumbing.com/en/stable/performance/

I need sharp version too as my project is heavily using sharpjs but need output ico format image. There is no active project is doing this. So I take this one to implement sharp version.
I am not going to publish this, but happy to share to you if you need this.
https://github.com/shtse8/sharp-to-ico/blob/main/index.ts

Big thanks to this project!
