### ISSUE TITLE
Fails checks of favicon checker

### ISSUE THREAD

**Issue by DanielRuf** [steambap/png-to-ico#7]
https://realfavicongenerator.net/favicon_checker says some things are not correct.

```
favicon.ico is missing some icons of recommended sizes (32x32)
Image favicon15.ico is ill-formed
```

After saving it with GIMP again the ill-formed check is resolved:

```
favicon.ico is missing some icons of recommended sizes (16x16, 32x32, 48x48)
```

**Comment by steambap** [comment]
My implementation was based on http://fileformats.wikia.com/wiki/Icon
somehow I can't open it today.
I guess I'll try to fix it tomorrow.

**Comment by steambap** [comment]
If I add 24x24 and 64x64 BMP, it will say 48x48 is missing. If I remove 256x256 BMP, it will say both 32x32 and 48x48 are missing. I have no idea how to make it pass the validator.

**Comment by steambap** [comment]
I was missing the "and map" for bmp and that's what realfavicongenerator.net is complaining about.

**Comment by DanielRuf** [comment]
Works great =)

![grafik](https://user-images.githubusercontent.com/827205/67559608-95253f00-f719-11e9-98cf-c11090ac1da0.png)
